% Build receptor grids and per-line numeric data (X, Y, Z, Elev, Hill)
% for each Z layer, and save everything in AERMODinputs/ReceptorMeta.mat.
%
% This script does NOT write any receptor text files. The runtime script
% (e.g., AutoAERMOD_03_RunAndCollect) will load ReceptorMeta.ReceptorMat{L}
% and print text lines like:
%    RE DISCCART X Y Z
% or RE DISCCART X Y Z ELEV HILLSCL
% as needed for AERMOD.
%
% ReceptorMeta fields:
%   recSpacing     - scalar (m)
%   xRange, yRange - [min max] (m)
%   zRange         - [min max] (m)
%   zLevels        - [1 x nZ] vector of layer heights (m)
%   xVals, yVals   - X/Y coordinates (consistent with grid)
%   nX, nY, nZ     - grid sizes
%   hasZdata       - logical
%   zDat           - [] or [N x 4] = [X, Y, Elev, HillScale]
%   ReceptorMat    - {nZ x 1} cell; each cell is [nRec x 5] numeric:
%                    [X, Y, Z, Elev, Hill], Elev/Hill = NaN if not used.
%
% Terrain input (optional, only if hasZdata = true):
%   zDat.mat must contain variable "zDat" as [N x 4]:
%     zDat(:,1) = X
%     zDat(:,2) = Y
%     zDat(:,3) = Elevation
%     zDat(:,4) = Hill-scale
%
% Haofei Yu, 2025-12-06

clear; clc; close all; fclose all; format compact; format longG;

%% ------------------------------------------------------------------------
%  User / domain settings
% -------------------------------------------------------------------------
recSpacing = 30;   % receptor spacing in m (X, Y, Z)
xRange     = [-3000 3000];
yRange     = [-3000 3000];
zRange     = [0 1500];

% One Z layer per recSpacing
zLevels = zRange(1):recSpacing:zRange(2);
nZ      = numel(zLevels);

%% ------------------------------------------------------------------------
%  Optional terrain / hill-scale data generated by AERMAP
% -------------------------------------------------------------------------
% If you have AERMAP terrain data, set hasZdata = true and ensure zDat.mat
% exists in the current directory (or adjust path below).
% Otherwise, set hasZdata = false and Elev/Hill will be stored as NaN.
hasZdata = false;   % set to false if you do NOT want terrain/hill

zDat = [];
if hasZdata
    tmp = load('zDat.mat');   % adjust path if needed
    if ~isfield(tmp,'zDat')
        error('zDat.mat must contain a variable named "zDat".');
    end
    zDat = tmp.zDat;          % [N x 4] = [X, Y, Elev, HillScale]
    if size(zDat,2) ~= 4
        error('zDat must be [N x 4] = [X, Y, Elev, HillScale].');
    end
end

%% ------------------------------------------------------------------------
%  Output folder for .mat (shared input folder for all scripts)
% -------------------------------------------------------------------------
inpFolder = fullfile(pwd, 'AERMODinputs');
if ~exist(inpFolder, 'dir')
    mkdir(inpFolder);
end

%% ------------------------------------------------------------------------
%  Build X/Y coordinate vectors
% -------------------------------------------------------------------------
xVals = xRange(1):recSpacing:xRange(2);
yVals = yRange(1):recSpacing:yRange(2);

% Ensure upper bounds included
if xVals(end) < xRange(2) && (xRange(2) - xVals(end)) > recSpacing * 1e-6
    xVals(end+1) = xRange(2);
end
if yVals(end) < yRange(2) && (yRange(2) - yVals(end)) > recSpacing * 1e-6
    yVals(end+1) = yRange(2);
end

nX = numel(xVals);
nY = numel(yVals);
nRecPerLayer = nX * nY;

% Tolerance for matching terrain data to grid points
if hasZdata && ~isempty(zDat)
    tolXY = recSpacing/2 + eps;
end

%% ------------------------------------------------------------------------
%  Preallocate storage for per-layer receptor matrices
% -------------------------------------------------------------------------
% ReceptorMat{L}: [nRecPerLayer x 5] = [X, Y, Z, Elev, Hill]
ReceptorMat = cell(nZ, 1);

%% ------------------------------------------------------------------------
%  Build numeric receptor data layer by layer
% -------------------------------------------------------------------------
for L = 1:nZ
    zHeight = zLevels(L);
    fprintf('Building receptors for layer %d / %d (Z = %.1f m)\n', ...
        L, nZ, zHeight);

    % Initialize matrix: [X Y Z Elev Hill]
    M = nan(nRecPerLayer, 5);
    idx = 0;

    for ix = 1:nX
        x = xVals(ix);
        for iy = 1:nY
            y = yVals(iy);
            z = zHeight;

            idx = idx + 1;
            M(idx,1) = x;
            M(idx,2) = y;
            M(idx,3) = z;

            if hasZdata && ~isempty(zDat)
                % Look up elevation and hill-scale from zDat
                dx  = abs(zDat(:,1) - x);
                dy  = abs(zDat(:,2) - y);
                % find the closest point
                ptDist = ( dx.^2 + dy.^2 ).^0.5;
                idxMatch = ptDist==min(ptDist);
                if min(ptDist) > recSpacing
                    error('Closest match is far away from (x,y) = (%.3f, %.3f).', x, y);
                else
                    M(idx,4) = mean( zDat(idxMatch,3) );  % Elevation
                    M(idx,5) = mean( zDat(idxMatch,4) );  % Hill-scale
                end
            else
                % No terrain data: leave Elev/Hill as NaN
                M(idx,4) = NaN;
                M(idx,5) = NaN;
            end
        end
    end
    ReceptorMat{L} = M;
end

%% ------------------------------------------------------------------------
%  Pack into struct and save to .mat
% -------------------------------------------------------------------------
ReceptorMeta = struct();
ReceptorMeta.recSpacing  = recSpacing;
ReceptorMeta.xRange      = xRange;
ReceptorMeta.yRange      = yRange;
ReceptorMeta.zRange      = zRange;
ReceptorMeta.zLevels     = zLevels;

ReceptorMeta.xVals       = xVals;
ReceptorMeta.yVals       = yVals;
ReceptorMeta.nX          = nX;
ReceptorMeta.nY          = nY;
ReceptorMeta.nZ          = nZ;

ReceptorMeta.hasZdata    = hasZdata;
ReceptorMeta.zDat        = zDat;          % keep if you may reuse terrain data

% Critical per-line receptor data: [X Y Z Elev Hill]
ReceptorMeta.ReceptorMat = ReceptorMat;   % {L}: [nRec x 5]

outMat = fullfile(inpFolder, 'ReceptorMeta.mat');
save(outMat, 'ReceptorMeta', '-v7.3');

fprintf('\nReceptorMeta saved to: %s\n', outMat);
fprintf('Each layer L has ReceptorMat{L}(:,1:5) = [X Y Z Elev Hill].\n');
